spring.application.name=complyx-api

spring.datasource.platform=postgres
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Generalo con openssl rand -base64 32
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh_expiration=86400000

logging.level.org.springframework.security=DEBUG
